#ifndef PINS_H_
#define PINS_H_

#define PWM_LEFT_FRONT (2)
#define FORWARD_LEFT_FRONT (24)
#define BACKWARD_LEFT_FRONT (22)
#define CODER_VCC_LEFT_FRONT (41)
#define CODER_A_LEFT_FRONT (37)
#define CODER_B_LEFT_FRONT (39)

#define PWM_RIGHT_FRONT (3)
#define FORWARD_RIGHT_FRONT (28)
#define BACKWARD_RIGHT_FRONT (26)
#define CODER_VCC_RIGHT_FRONT (35)
#define CODER_A_RIGHT_FRONT (33)
#define CODER_B_RIGHT_FRONT (31)

#define PWM_LEFT_BACK (5)
#define FORWARD_LEFT_BACK (34)  
#define BACKWARD_LEFT_BACK (36)
#define CODER_VCC_LEFT_BACK (53)
#define CODER_A_LEFT_BACK (49)
#define CODER_B_LEFT_BACK (51)

#define PWM_RIGHT_BACK (4)
#define FORWARD_RIGHT_BACK (30)
#define BACKWARD_RIGHT_BACK (32)
#define CODER_VCC_RIGHT_BACK (47)
#define CODER_A_RIGHT_BACK (45)
#define CODER_B_RIGHT_BACK (43)

#define SONAR_VCC_PIN (0)
#define SONAR_TRIG_PIN (13)
#define SONAR_ECHO_PIN (12)

#define BACK_PIN (50)
#define ANALOG_READ_PIN (A0)

#endif
